apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: manim-studio-frontend
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: "10"
        autoscaling.knative.dev/minScale: "1"
        run.googleapis.com/cpu-throttling: "true"
        run.googleapis.com/execution-environment: gen2
    spec:
      containerConcurrency: 100
      timeoutSeconds: 60
      containers:
      - image: gcr.io/PROJECT_ID/manim-studio-frontend:latest
        ports:
        - name: http1
          containerPort: 80
        env:
        - name: VITE_BACKEND_URL
          value: "https://manim-studio-backend-SERVICE_HASH-uc.a.run.app"
        - name: VITE_SUPABASE_URL
          valueFrom:
            secretKeyRef:
              key: supabase-url
              name: manim-studio-secrets
        - name: VITE_SUPABASE_ANON_KEY
          valueFrom:
            secretKeyRef:
              key: supabase-anon-key
              name: manim-studio-secrets
        - name: VITE_STRIPE_PUBLISHABLE_KEY
          valueFrom:
            secretKeyRef:
              key: stripe-publishable-key
              name: manim-studio-secrets
        resources:
          limits:
            cpu: "1"
            memory: "512Mi"
          requests:
            cpu: "0.5"
            memory: "256Mi"
        startupProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          timeoutSeconds: 3
          periodSeconds: 5
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          timeoutSeconds: 3
          periodSeconds: 30
  traffic:
  - percent: 100
    latestRevision: true