apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: manim-studio-worker
  annotations:
    run.googleapis.com/ingress: internal
    run.googleapis.com/ingress-status: internal
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: "5"
        autoscaling.knative.dev/minScale: "0"
        run.googleapis.com/cpu-throttling: "false"
        run.googleapis.com/execution-environment: gen2
    spec:
      containerConcurrency: 10
      timeoutSeconds: 600
      containers:
      - image: gcr.io/PROJECT_ID/manim-studio-worker:latest
        ports:
        - name: http1
          containerPort: 8001
        env:
        - name: TEMP_DIR
          value: "/tmp/manim_temp"
        resources:
          limits:
            cpu: "4"
            memory: "4Gi"
          requests:
            cpu: "2"
            memory: "2Gi"
        volumeMounts:
        - name: temp-storage
          mountPath: /tmp/manim_temp
        startupProbe:
          httpGet:
            path: /health
            port: 8001
          initialDelaySeconds: 15
          timeoutSeconds: 10
          periodSeconds: 10
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /health
            port: 8001
          initialDelaySeconds: 30
          timeoutSeconds: 10
          periodSeconds: 60
      volumes:
      - name: temp-storage
        emptyDir:
          sizeLimit: 2Gi
  traffic:
  - percent: 100
    latestRevision: true